# Workflow script
name: cml_run

env:
  PYTHON_VERSION: 3.8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute ML workflow
        run: |
          python train.py

      - name: Generate report
        run: |
          python generate_report.py

      - name: Send report as a comment
        run: |
          cml-send-comment report.md
